#!/usr/bin/expect -f
set timeout 1
set host [lindex $argv 0]
set port [lindex $argv 1]

spawn ./atom_supplier $host $port

expect {
    "Connected to server" {}
    timeout { puts " Failed to connect to server"; exit 1 }
}

set f [open "commands1.txt"]
while {[gets $f line] >= 0} {
    send -- "$line\r"
    expect {
        -re ".*" {}
        timeout {}
    }
    sleep 0.1
}
close $f

sleep 1
send -- "\004"  ;# 
expect eof
