# Makefile for part3
CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++17

# Targets
TARGETS = atom_supplier drinks_bar molecule_requester

all: $(TARGETS)

atom_supplier: atom_supplier.cpp
	$(CXX) $(CXXFLAGS) -o $@ $<

drinks_bar: drinks_bar.cpp
	$(CXX) $(CXXFLAGS) -o $@ $<

molecule_requester: molecule_requester.cpp
	$(CXX) $(CXXFLAGS) -o $@ $<

clean:
	rm -f $(TARGETS)
